[project]
name = 'Blockchain-Enabled-Specialized-Medical-Equipment-Maintenance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.device-registration]
path = 'contracts/device-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.maintenance-scheduling]
path = 'contracts/maintenance-scheduling.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
